### ISSUE TITLE
Render markdown in report previewer

### ISSUE THREAD

**Issue by asbates** [insightsengineering/teal.reporter#158]
Have the report previewer (`reporter_previewer_srv`) render markdown from a `TextBlock` object content. This is the comment users can add to when they click 'add report card'. So allow users to put markdown in these comments and have this render in the report previewer.

See #155 for a starting point. This was started there but it ended up going beyond the scope of the PR and original issue #71.

**Comment by donyunardi** [comment]
@lcd2yyz 
Would it be value added to have markdown rendering capability as user add cards and insert their comment when using the Reporter feature?

**Comment by asbates** [comment]
To be clear, this issue regards enabling markdown in the report previewer. So in the app itself.

We can use markdown and have it rendered in the downloaded report. As of now though, it would show as unformatted markdown in the app.

**Comment by lcd2yyz** [comment]
I see thanks for the clarification.
Then what is the reason for using different rendering mechanism between previewer and the actual report? Is there a technical barrier to use the same? After all the intention of previewer is to show the users “what you see is what you get”.

**Comment by asbates** [comment]
I don't know the reason (new to the team) but @Polkas can probably answer that.


As far as "Is there a (and if so, what is the) technical difficulty in enabling both at this point?" enabling markdown will give us the line break functionality. So the technical difficulty is limited to markdown. However, line breaking on it's own can be done without markdown (#155).

**Comment by Polkas** [comment]
This issue is only a backlog one, nice to have (think about) feature. 
"Then what is the reason for using different rendering mechanism between previewer and the actual report?".
Report is a document of some type like pdf or html, and Previewer is the interactive GUI (Graphical user interface) to build collections of cards which are later materialized to some document.  Previewer enable ordering and removal of already added cards. In future we want to add more features to Previewer. These two elements are totally different. Document could be rendered even without Previewer like with the DownloadModule (one of the 3 buttons in each module with reporter). Previewer was made to offer more clear and easier document creation process.
From technical point of view the Renderer which render document convert the cards to rmarkdown and PreviewerModule converts the cards to html (GUI). This processes are properly encapsulated and nothing is done without need.

**Comment by donyunardi** [comment]
Thanks for the explanation @Polkas, this is clear to me.

From that I gather so far, this feature doesn't feel like a priority to me since #155 will already fix the initial objective.
If it's okay, I'd like to propose that we put this to rest and resurface when needed.
